music/urls.py
from django.conf.urls import url
from . import views

app_name ='music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'), # request nothing ^$

    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'), # 'detail' is the url request pattern: r'^(?P<album_id>[0-9]+)/$', now go find your response in views.detail
    # /music/<album_id>/favoite
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')

    # /music/album/add/    ...a form generated
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),  # django looks for pattern that matches url
    url(r'^music/', include('music.urls')) # the request of music url has a response: music/urls.py, include(file.py)
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk}) # Assigned a PK, no need to add anything, all in automation 

    def __str__(self): # a string representation of Album object
        return self.album_title + '-' + self.artist


class song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)

    def __str__(self): # a string representation of Album object
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . models import Album

class IndexView(generic.ListView): # inherent from type ListView
    template_name='music/index.html'
    context_object_name='all_albums' # override object_list

    def get_queryset(self):         # query the dataset
        return Album.objects.all()  # return as a object_list

class DetailView(generic.DetailView):
    model=Album # what model/databaseObject are you trying to get details of?
    template_name='music/detail.html' # HttpResponse

# Generating a Model form, inherent from CreateView Class
class AlbumCreate(CreateView):
    model=Album
    fields=['artist', 'album_title', 'genre', 'album_logo'] # field is an object used in templates


# from django.http import HttpResponse
# from django.http import Http404
# from django.template import loader
# from django.shortcuts import render, get_object_or_404
# from . models import Album


# def index(request): # views function
#
#     all_albums=Album.objects.all()
#     # template = loader.get_template('music/index.html') # Provides templates to views.py
#     context = {
#         'all_albums': all_albums # A dictionary of the Album objects in database that the template needs to work behinde scene
#     }
#     return render(request, 'music/index.html', context) # A built in HttpResponse in render()
#
#     # html=''
#     # for i in all_albums:
#     #     url='/music/' + str(i.id) + '/'
#     #     html += '<a href="' + url + '">' + i.album_title + '</a><br>'
#     # return HttpResponse(template.render(context, request)) # Give the response to user's request in url
#
# def detail(request, album_id):
#
#     # return HttpResponse("<h2>Detailes for Album id: " + str(album_id) + "</h2>")
#     # try:
#     #     album=Album.objects.get(pk=album_id)
#     #
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does not exist!")
#
#     album=get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album':album}) # model access, album class in return
#
# def favorite(request, album_id):
#     album=get_object_or_404(Album,pk=album_id)
#     try:
#         selected_song=album.song_set.get(pk=request.POST['song'])
#     except (KeyError, song.DoesNotExist):
#         return(request, 'music/detail.html', {'album':album,
#                                               'error_message':"You did not select a valid song."})
#
#     else:
#         selected_song.is_favorite=True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album':album})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                                
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}So Cool!{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">So Cool!</a>

        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>

                </li>


            </ul>
            <form class="navbar-form navbar-left" role="search" medhod="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">


                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>

                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>

            </ul>
        </div>


    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="#">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>

                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}﻿

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <!-- Actual input area is field object -->
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    {% if all_albums %}
        <h3>Here are all my stuff</h3>
        <ul>
            {% for i in all_albums %}
            <!--Change the hard code-->
            <li><a href="{% url 'music:detail' i.id %}">{{ i.album_title }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <h3>You don't have any albums!</h3>
    {% endif %}

{% endblock %}